updated autoabel

diff --git a/.github/workflows/autolabel.yaml b/.github/workflows/autolabel.yaml
--- a/.github/workflows/autolabel.yaml
+++ b/.github/workflows/autolabel.yaml
@@ -21,7 +21,7 @@ jobs:
           configuration-path: .github/labeler.yml
           sync-labels: true
   
-  check-changelog:
+  check-changelog-based-on-labels:
     needs: label
     if: contains(needs.label.outputs.all-labels, 'release')
     runs-on: ubuntu-latest
@@ -46,7 +46,7 @@ jobs:
 
           echo "pr_body= $pr_body"
           echo "pr_title= $pr_title"
-          
+
           version_regex="v([0-9]+)\.([0-9]+)\.([0-9]+)"
 
           if [[ $pr_body =~ $version_regex ]]; then
@@ -95,4 +95,68 @@ jobs:
           else
             echo "Version $version found in CHANGELOG.md."
           fi
+  check-changelog:
+    needs: label
+    if: contains(needs.label.outputs.all-labels, 'release')
+    runs-on: ubuntu-latest
+    steps: 
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0 
+
+      - name: Get Latest Tag
+        id: get-latest-tag
+        run: |
+          git fetch --tags
           
+          # Get the latest tag, or initialize to v0.0.0 if no tags are found
+          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
+          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
+
+      - name: Determine New Version from CHANGELOG
+        id: determine-new-version
+        run: |
+          latest_tag=${{ env.latest_tag }}
+
+          # Extract the latest version from CHANGELOG.md
+          changelog_version=$(grep -oP '^## \[\K[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -n 1)
+
+          if [ -z "$changelog_version" ]; then
+            echo "No version found in CHANGELOG.md."
+            exit 1
+          fi
+
+          # Ensure changelog_version is greater than latest_tag
+          if [ "$(printf '%s\n' "$changelog_version" "$latest_tag" | sort -V | head -n1)" = "$changelog_version" ] && [ "$changelog_version" != "$latest_tag" ]; then
+            echo "The version in CHANGELOG.md ($changelog_version) is not greater than the latest tag ($latest_tag)."
+            exit 1
+          fi
+
+          clean_version="${changelog_version#v}"
+          echo "version=$clean_version" >> $GITHUB_ENV
+          echo "Version determined from CHANGELOG.md: $clean_version"
+
+      - name: Check if Version Already Exists in Tags
+        if: steps.determine-new-version.conclusion != 'skipped'
+        run: |
+          version="${{ env.version }}"
+          if git tag --list | grep -q "^$version$"; then
+            echo "Version $version already exists in tags."
+            exit 1
+          else
+            echo "Version $version does not exist in tags."
+          fi
+
+      - name: Validate Version in CHANGELOG
+        id: validate-version-in-changelog
+        if: steps.determine-new-version.conclusion != 'skipped'
+        run: |
+          version="${{ env.version }}"
+          if ! grep -q "^## \[$version\]" CHANGELOG.md; then
+            echo "Version $version not found in CHANGELOG.md."
+            exit 1
+          else
+            echo "Version $version found in CHANGELOG.md."
+          fi
+            
