check applied labels

diff --git a/.github/workflows/autolabel.yaml b/.github/workflows/autolabel.yaml
--- a/.github/workflows/autolabel.yaml
+++ b/.github/workflows/autolabel.yaml
@@ -11,11 +11,6 @@ jobs:
       contents: read
       pull-requests: write
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
       - name: Apply Labels
         id: label-the-PR
         uses: actions/labeler@v5
@@ -23,64 +18,77 @@ jobs:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           configuration-path: .github/labeler.yml
           sync-labels: true
-
-      - name: Check Version in Changelog for release
-        id: check-version-in-changelog
-        if: contains(steps.label-the-PR.outputs.all-labels, 'release')
+      - name: Get Applied Labels
+        id: get-labels
         run: |
-          # Fetch the latest tags from the remote
-          git fetch --tags
+          echo ${{ steps.label-the-PR.outputs.all-labels }}
+  
+    # check-changelog:
+    #   needs: label
 
-          # Get the latest tag, or initialize to v0.0.0 if no tags are found
-          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
+      
+    #   steps: 
+    #   - name: Checkout Repository
+    #       uses: actions/checkout@v4
+    #       with:
+    #         fetch-depth: 0    
+    #   - name: Check Version in Changelog for release
+    #     id: check-version-in-changelog
+    #     if: contains(steps.label-the-PR.outputs.all-labels, 'release')
+    #     run: |
+    #       # Fetch the latest tags from the remote
+    #       git fetch --tags
 
-          # Extract version from PR title or body
-          pr_body="${{ github.event.pull_request.body }}"
-          pr_title="${{ github.event.pull_request.title }}"
-          version_regex="v([0-9]+)\.([0-9]+)\.([0-9]+)"
+    #       # Get the latest tag, or initialize to v0.0.0 if no tags are found
+    #       latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
 
-          if [[ $pr_body =~ $version_regex ]]; then
-            major=${BASH_REMATCH[1]}
-            minor=${BASH_REMATCH[2]}
-            patch=${BASH_REMATCH[3]}
-            new_tag="v$major.$minor.$patch"
-          elif [[ $pr_title =~ $version_regex ]]; then
-            major=${BASH_REMATCH[1]}
-            minor=${BASH_REMATCH[2]}
-            patch=${BASH_REMATCH[3]}
-            new_tag="v$major.$minor.$patch"
-          else
-            # Split the latest tag into parts
-            IFS='.' read -r -a parts <<< "${latest_tag#v}"
-            major=${parts[0]}
-            minor=${parts[1]}
-            patch=${parts[2]}
-            patch=$((patch + 1))
-            new_tag="v$major.$minor.$patch"
-          fi
+    #       # Extract version from PR title or body
+    #       pr_body="${{ github.event.pull_request.body }}"
+    #       pr_title="${{ github.event.pull_request.title }}"
+    #       version_regex="v([0-9]+)\.([0-9]+)\.([0-9]+)"
 
-          clean_version="${new_tag#v}"
-          echo "version=$clean_version" >> $GITHUB_ENV
-          echo "Version determined: $clean_version"
+    #       if [[ $pr_body =~ $version_regex ]]; then
+    #         major=${BASH_REMATCH[1]}
+    #         minor=${BASH_REMATCH[2]}
+    #         patch=${BASH_REMATCH[3]}
+    #         new_tag="v$major.$minor.$patch"
+    #       elif [[ $pr_title =~ $version_regex ]]; then
+    #         major=${BASH_REMATCH[1]}
+    #         minor=${BASH_REMATCH[2]}
+    #         patch=${BASH_REMATCH[3]}
+    #         new_tag="v$major.$minor.$patch"
+    #       else
+    #         # Split the latest tag into parts
+    #         IFS='.' read -r -a parts <<< "${latest_tag#v}"
+    #         major=${parts[0]}
+    #         minor=${parts[1]}
+    #         patch=${parts[2]}
+    #         patch=$((patch + 1))
+    #         new_tag="v$major.$minor.$patch"
+    #       fi
 
-      - name: Check if Version Already Exists in Tags
-        run: |
-          version="${{ env.version }}"
-          if git tag --list | grep -q "^$version$"; then
-            echo "Version $version already exists in tags."
-            exit 1
-          else
-            echo "Version $version does not exist in tags."
-          fi
+    #       clean_version="${new_tag#v}"
+    #       echo "version=$clean_version" >> $GITHUB_ENV
+    #       echo "Version determined: $clean_version"
 
-      - name: Check Version in CHANGELOG
-        id: check_version
-        run: |
-          version="${{ env.version }}"
-          if ! grep -q "^## \[$version\]" CHANGELOG.md; then
-            echo "Version $version not found in CHANGELOG.md."
-            exit 1
-          else
-            echo "Version $version found in CHANGELOG.md."
-          fi
+    #   - name: Check if Version Already Exists in Tags
+    #     run: |
+    #       version="${{ env.version }}"
+    #       if git tag --list | grep -q "^$version$"; then
+    #         echo "Version $version already exists in tags."
+    #         exit 1
+    #       else
+    #         echo "Version $version does not exist in tags."
+    #       fi
+
+    #   - name: Check Version in CHANGELOG
+    #     id: check_version
+    #     run: |
+    #       version="${{ env.version }}"
+    #       if ! grep -q "^## \[$version\]" CHANGELOG.md; then
+    #         echo "Version $version not found in CHANGELOG.md."
+    #         exit 1
+    #       else
+    #         echo "Version $version found in CHANGELOG.md."
+    #       fi
           
